all:
	@+make -j 4 -C ../

eog:
	@make eog -C ../

force:
	@make clean all

test:
	@make run eog

lib:
	@make lib -C ../

run:
	@make run -C ../

vg:
	@make vg -C ../

gdb:
	@make gdb -C ../

killall:
	@make killall -C ../

clean:
	@make clean -C ../
